# Generated by Django 2.0.2 on 2020-07-13 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuisine', multiselectfield.db.fields.MultiSelectField(choices=[('American', 'American'), ('Chinese', 'Chinese'), ('European', 'European'), ('Greek', 'Greek'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Thai', 'Thai'), ('Lebanese', 'Lebanese')], default='', max_length=68)),
                ('Lifestyle', multiselectfield.db.fields.MultiSelectField(choices=[('Fashion', 'Fashion'), ('Car Rental', 'Car Rental'), ('Nightlife', 'Nightlife'), ('Luxury Purchase', 'Luxury Purchase'), ('Business & Corporate', 'Business & Corporate'), ('Gastronomy', 'Gastronomy'), ('Career Counseling for Kids', 'Career Counseling for Kids')], default='', max_length=103)),
                ('Travel', multiselectfield.db.fields.MultiSelectField(choices=[('Nature & Outdoors', 'Nature & Outdoors'), ('Family', 'Family'), ('Weekend Getaways', 'Weekend Getaways'), ('Desert Safari', 'Desert Safari'), ('Safari', 'Safari'), ('Historical & Heritage', 'Historical & Heritage'), ('Romantic Getaways', 'Romantic Getaways')], default='', max_length=102)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
