# Generated by Django 2.0.2 on 2020-07-13 12:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200713_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Cuisine',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('American', 'American'), ('Chinese', 'Chinese'), ('European', 'European'), ('Greek', 'Greek'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Thai', 'Thai'), ('Lebanese', 'Lebanese')], default='', max_length=68, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Lifestyle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fashion', 'Fashion'), ('Car Rental', 'Car Rental'), ('Nightlife', 'Nightlife'), ('Luxury Purchase', 'Luxury Purchase'), ('Business & Corporate', 'Business & Corporate'), ('Gastronomy', 'Gastronomy'), ('Career Counseling for Kids', 'Career Counseling for Kids')], default='', max_length=103, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Travel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Nature & Outdoors', 'Nature & Outdoors'), ('Family', 'Family'), ('Weekend Getaways', 'Weekend Getaways'), ('Desert Safari', 'Desert Safari'), ('Safari', 'Safari'), ('Historical & Heritage', 'Historical & Heritage'), ('Romantic Getaways', 'Romantic Getaways')], default='', max_length=102, null=True),
        ),
    ]
