# Generated by Django 2.0.2 on 2020-07-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200713_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Cuisine',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Lifestyle',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Travel',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
