# Generated by Django 2.0.2 on 2020-07-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200713_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Hotel',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Cuisine',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Lifestyle',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Travel',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
