# Generated by Django 2.0.2 on 2020-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200717_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Hotel',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
